name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]  # Update this according to your project requirements.

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install Dependencies
      run: npm ci

    - name: Build Project
      run: npm run build --if-present

    - name: Run Tests
      run: npm test

    - name: Deploy to Server via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.4
      with:
        server: ${{ secrets.GIT_CPANEL_REACT_SERVER }}
        host: ${{ secrets.GIT_CPANEL_REACT_HOST }}
        username: ${{ secrets.GIT_CPANEL_REACT_USERNAME }}
        password: ${{ secrets.GIT_CPANEL_REACT_PASSWORD }}
        port: ${{ secrets.GIT_CPANEL_REACT_PORT }}  # Often this is 21 for FTP, adjust if different.
        local-dir: ./build/  # Adjust this based on where your build artifacts are output.
